#ifndef TEXTBOX_H
#define TEXTBOX_H 1

//#include "coordinate.h"
#include "colour.h"
#include <string>
#include "config.h"
#include <opencv2/imgproc.hpp>
#include <vector>

#include <opencv2/core/types.hpp>
using namespace cv;

#define BOX_THICKNESS_OFFSET 2

// faster squaring than the maths lib
#define SQUARE(x) ((x)*(x))

class Textbox {
    public:
    
    Textbox(){}


    // new constructors with opencv box
    Textbox(std::vector<Point> points, std::string text, Config* config);

    // calc text colour given background colour
    Colour calc_text_colour(Colour background_colour);

    // scale text box
    void scale(double scale_factor);

    // text colour and text content
    //Colour colour;
    std::string text;


    // variables related to new constructor
    Point top_left;
    Point top_right;
    Point bottom_left;
    Point bottom_right;

    // for sorting
    int rank;
    int v_rank;

    // some more stuff that will be generated by the constructor
    Point mid_left;
    Point mid_right;

    Point center;

    // text related stuff
    int box_height;
    int box_width;

    // for inpainting
    int box_thickness;

    // for debug
    std::string to_string();

    private:
    Point midpoint(Point a, Point b);
};


bool compare_textbox(Textbox t1, Textbox t2);

#endif