#ifndef TEXTBOX_H
#define TEXTBOX_H 1

//#include "coordinate.h"
#include "colour.h"
#include <string>
#include <vector>

#include <opencv2/core/types.hpp>
using namespace cv;

#define BOX_THICKNESS_OFFSET 2

#define TOP_LEFT_INDEX 1
#define TOP_RIGHT_INDEX 2
#define BOTTOM_LEFT_INDEX 0
#define BOTTOM_RIGHT_INDEX 3

// faster squaring than the maths lib
#define SQUARE(x) ((x)*(x))

class Textbox {
    public:
    
    Textbox(){}


    // new constructors with opencv box
    Textbox(std::vector<Point> points, std::string text);

    // calc text colour given background colour
    Colour calc_text_colour(Colour background_colour);

    // scale text box
    void scale(double scale_factor);

    // text colour and text content
    //Colour colour;
    std::string text;


    // variables related to new constructor
    Point top_left;
    Point top_right;
    Point bottom_left;
    Point bottom_right;

    // some more stuff that will be generated by the constructor
    Point mid_left;
    Point mid_right;

    Point center;

    // text related stuff
    int box_height;
    int box_width;

    // for inpainting
    int box_thickness;

    // some old stuff
    /*
    // old constructors.
    Textbox(Coordinate topleft, Coordinate topright, Coordinate bottomleft, Coordinate bottomright);
    Textbox(Coordinate topleft, Coordinate topright, Coordinate bottomleft, Coordinate bottomright, std::string text);
    Textbox(Coordinate topleft, Coordinate topright, Coordinate bottomleft, Coordinate bottomright, std::string text, Colour colour);

    // old geters
    Coordinate get_top_left();
    Coordinate get_top_right();
    Coordinate get_bottom_left();
    Coordinate get_bottom_right();

    std::string get_text();
    Colour get_colour();
    
    // old coords
    Coordinate topleft;
    Coordinate topright;
    Coordinate bottomleft;
    Coordinate bottomright;
    */

    private:
    Point midpoint(Point a, Point b);
};

#endif